### ISSUE TITLE
Add Start of Speech vad_events to JS SDK

### ISSUE THREAD

**Issue by jpvajda** [deepgram/deepgram-js-sdk#232]
see docs for more info: https://developers.deepgram.com/docs/start-of-speech-detection

New API Param: vad_events

**Comment by pBread** [comment]
Also would like to see this added

**Comment by jpvajda** [comment]
@pBread  Thanks for letting us know! We have a PR to introduce this feature into the SDK, it's currently in review:

https://github.com/deepgram/deepgram-js-sdk/pull/235
