### ISSUE TITLE
Increase in `UND_ERR_HEADERS_TIMEOUT` errors

### ISSUE THREAD

**Issue by mosnicholas** [deepgram/deepgram-js-sdk#243]
## What is the current behavior?
In periods of high load, response times fluctuate. If they go over 5' mark, the fetch library implemented fails, because it cannot stay alive for longer than 5'. Those timeouts are also not configurable.

This is a [known limitation](https://github.com/nodejs/node/issues/46375) of the fetch library implemented.

## Steps to reproduce
It's ad-hoc and depends on response rates & usage of Deepgram's servers

## Expected behavior
That we don't see timeout issues and can configure timeout values if needed.

## Please tell us about your environment
- **Operating System/Version:** Mac
- **Language:** [TypeScript]
- **Browser:** Chrome

This is from calls made server side

## Other information
![Screenshot 2024-01-30 at 9 04 32 AM](https://github.com/deepgram/deepgram-js-sdk/assets/3606778/efa54801-3a99-48c0-9901-090507735c78)

**Comment by lukeocodes** [comment]
the solution #245 has now provided the ability to override fetch with a custom fetch interface
