### ISSUE TITLE
REMOTE_CONTENT_ERROR: The remote server hosting the media failed to return valid data

### ISSUE THREAD

**Issue by onosendi** [deepgram/deepgram-js-sdk#263]
I'm getting the error given in the title with the code shown below. This error occurs using the same URL, and happens every once and a while. So in other words, sometimes it works, sometimes it doesn't. There is nothing wrong with the remote URL either. Any ideas?

```javascript
const deepgram = createClient(config.deepgram.api_key);

async function send_deepgram_request(url) {
    const options = {
        model: 'nova-2-phonecall',
        summarize: 'v2',
        diarize: true,
        redact: 'pci',
        smart_format: true,
        numerals: true,
    };

    const { result, error } = await deepgram
        .listen
        .prerecorded
        .transcribeUrlCallback(
            { url },
            new CallbackUrl(config.deepgram.webhook),
            options,
        );

    return { result, error };
}
```

**Comment by lukeocodes** [comment]
Closing as this is an API issue. If you'd like to raise a message on the community discord, or github discussion forum, you may find an explanation.

This is usually related to external factors though, like the speed of the host's internet, any outages in the middle, etc. Rarely do we have this issue on our service, as it would impact _a lot_ of customers for our internet to be slow.
