### ISSUE TITLE
Deegram doesn't detect speech end

### ISSUE THREAD

**Issue by kvssankar** [deepgram/deepgram-js-sdk#281]
In speech to text, **When numbers are spoken fast** and smart format is true, and endpoint is 1000ms. Even after unlimited silence, is_final or speech_final never becomes true. Utterance end also is never detected.

let request: any = {
  language: "en",
  encoding: "mulaw",
  sample_rate: "8000",
  model: "enhanced-phonecall",
  punctuate: true,
  interim_results: true,
  endpointing: 1000,
  utterance_end_ms: 1000,
  filler_words: true,
  smart_format: true,
};

**Comment by lukeocodes** [comment]
Can you try nova-2 to see if it occurs there?
