### ISSUE TITLE
Transitive dependency on es5-ext causes socket.dev / snyk errors

### ISSUE THREAD

**Issue by lox** [deepgram/deepgram-js-sdk#288]
## What is the current behavior?

Currently due to `websocket` having a dependency on `es5-ext` the deepgram package is causing failures in builds that rely on socket.dev and snyk for dependency scanning. 

The issues is that [es5-ext publishes protest banners](https://github.com/medikoo/es5-ext/issues/116). I have zero interest in the politics, but from my perspective it's a breach of trust that makes it a supply chain risk. 

## Steps to reproduce

Run a build with socket.dev.

<img width="1299" alt="image" src="https://github.com/deepgram/deepgram-js-sdk/assets/15758/6e7484f4-8629-491f-a6f1-35017cf0b396">

See https://socket.dev/npm/package/@deepgram/sdk

## Expected behavior

No critical errors. 

## Fixes

This can be resolved by adding this to your package.json:

```
  "resolutions": {
    "es5-ext": "0.10.53"
  },
```

**Comment by lukeocodes** [comment]
Wow, thanks. I'll review this first thing and get a patch out

We have a draft PR for removing that websocket library, should be released as 3.4.x this week

**Comment by lukeocodes** [comment]
release for this and another vuln just pushed out
