### ISSUE TITLE
Calling rest api from supabase edge function trigger CORS error 

### ISSUE THREAD

**Issue by wliumelb** [deepgram/deepgram-js-sdk#291]
## What is the current behavior?

Calling transcribeUrl api from deployed supabase edge function return CORS error:

Due to CORS we are unable to support REST-based API calls to our API from the browser. Please consider using a proxy, and including a `restProxy: { url: ''}` in your Deepgram client options.

## Steps to reproduce
run this function from deployed supabase edge function
```
import { createClient } from "https://esm.sh/@deepgram/sdk@3.3.2";
import { deepgramApiKey } from "../_shared/deepgram_key.ts";

export const transcribeRecording = async (input: {
  url: string
}) => {
  const { url } = input;

  const deepgram = createClient(deepgramApiKey);

  const { result, error } = await deepgram.listen.prerecorded.transcribeUrl(
    {
      url,
    },
    {
      model: "nova-2",
      detect_language: true,
      paragraphs: true,
    }
  );
};
```

## Expected behavior

CORS error should not be triggered as it is not in a browser

## Please tell us about your environment

Supabase edge runtime

## Other information

The bug is caused by this line of code:
https://github.com/deepgram/deepgram-js-sdk/blob/875650806ba46fc48adc817d44df48227771b2eb/src/lib/helpers.ts#L17

In the supabase edge run time, the 'window' global variable is an object rather than undefined

**Comment by lukeocodes** [comment]
Nice, it's hard for us to test all these different edge runtimes. I'll think about a better way to determine whether we require a proxy or not

**Comment by rallu** [comment]
Same problem with using Deno Deploy. I suggest reducing the number of checks for "stupid user" errors.

**Comment by lukeocodes** [comment]
> Same problem with using Deno Deploy. I suggest reducing the number of checks for "stupid user" errors.

I think you under-estimate how many people would try to use this in the browser for rest requests, when our API does not support custom origins for CORS. you'd always need to proxy it.

**Comment by vb-cv** [comment]
Hi @lukeocodes , sorry to bother again on this, but I just started using deepgram today, on supabase, and I get the exact same error. I see this seems to be closed and fixed but I wonder, do I need to anything to get that fix working in Supabase?

This is how I get a client:

 this.deepgram = createClient(Deno.env.get("DEEPGRAM_API_KEY"), {
            endpoint: config.DEEPGRAM_API_URL,
        });


This is how I use it:        
 const { result, error } = await this.deepgram.listen.prerecorded
            .transcribeUrl(
                {
                    url: url,
                },
                {
                    model: "nova-2",
                    language: "end",
                    punctuate: true,
                    paragraphs: true,
                },
            );

Any help much appreciated.
