### ISSUE TITLE
process is undefined on v3.3.1

### ISSUE THREAD

**Issue by lukeocodes** [deepgram/deepgram-js-sdk#297]
There are occations where process is still undefined when using a non-webpack app. we need a solution that doesn't rely on a webpack plugin

**Comment by lukeocodes** [comment]
related to #274

**Comment by noxan** [comment]
@lukeocodes seems you already fixed the issue with https://github.com/deepgram/deepgram-js-sdk/commit/bd51da7ce06c59b3dea55e4a915e802bd43a3754 :)
