### ISSUE TITLE
STT is broken in 3.4.0 and up (returns 401 error)

### ISSUE THREAD

**Issue by orgads** [deepgram/deepgram-js-sdk#321]
## What is the current behavior?

On `client.listen.live(settings)`, with a valid key, I get 401 error. This works fine with version 3.3.4.

## Other information

This results from a tiny behavioral change between `websocket` and `ws` packages, on `protocols` handling.

The related change is #293.

Before this change, `w3cwebsocket` was used. This package joins the `protocols` in `Sec-WebSocket-Protocol` with `', '` (comma followed by a space). See [here](https://github.com/theturtle32/WebSocket-Node/blob/d87afb7ef28f9c2249aa764805af87846d46f522/lib/WebSocketClient.js#L200):
```js
reqHeaders['Sec-WebSocket-Protocol'] = this.protocols.join(', ');
```

Now, this has been replaced with `ws`, which has no space between the values. See [here](https://github.com/websockets/ws/blob/019f28ff1ffddfcdc428d1de5ecd98648057a2ab/lib/websocket.js#L777):
```js
opts.headers['Sec-WebSocket-Protocol'] = protocols.join(',');
```

Apparently the server side is sensitive for this change, and rejects the request.

I confirmed this by modifying `ws` to use `', '`, and the issue was resolved.

**Comment by lukeocodes** [comment]
This is strange, as our real-time examples work in testing. I wonder if this somehow runtime specific, too?

This was our change in this SDK

https://github.com/deepgram/deepgram-js-sdk/blob/main/src/packages/AbstractLiveClient.ts#L125-L129

**Comment by orgads** [comment]
Is it possible to fix this on the server? See https://github.com/websockets/ws/pull/2244#issuecomment-2245214238

**Comment by lukeocodes** [comment]
That's odd, as we use `ws` for node runtime websockets in the SDK. Can you tell me anything else about your environment?

**Comment by lukeocodes** [comment]
> Is it possible to fix this on the server? See [websockets/ws#2244 (comment)](https://github.com/websockets/ws/pull/2244#issuecomment-2245214238)

I believe this refers to your server, when you're running the SDK code. I am not sure how. As I said, we run node example code in multiple versions and this has never come up

**Comment by orgads** [comment]
It's exactly where you pointed. `NATIVE_WEBSOCKET_AVAILABLE` is true if `WebSocket` is defined. Since I assign `global.WebSocket = WebSocket` then in my case it is defined.

I use the default deepgram api server, didn't configure anything special. This reproduces with your example, just add these 2 lines at the file header.

**Comment by lukeocodes** [comment]
> It's exactly where you pointed. `NATIVE_WEBSOCKET_AVAILABLE` is true if `WebSocket` is defined. Since I assign `global.WebSocket = WebSocket` then in my case it is defined.
> 
> I use the default deepgram api server, didn't configure anything special. This reproduces with your example, just add these 2 lines at the file header.

The library maintainer (if that is who is replying) is suggesting to you that all API vendors, including Deepgram, which serve millions of requests per hour, make this flexible. Flexible code has a performance overhead. I challenge his suggestion that this is effectively a bug in our API.

**Comment by orgads** [comment]
While I see your point, he is right that servers should conform to the RFC and not make assumptions about the input. The performance overhead is negligible for this kind of parsing.

**Comment by orgads** [comment]
I have to say that actually *stripping out* the space should have performance impact more than handling a header without a space. Did you check the server logic?

**Comment by lukeocodes** [comment]
> I have to say that actually _stripping out_ the space should have performance impact more than handling a header without a space. Did you check the server logic?

Ok

**Comment by lpinca** [comment]
> I have to say that actually stripping out the space should have performance impact more than handling a header without a space. Did you check the server logic?

This is the reason why we removed it in `ws@8` and because less bytes are sent over the wire without multiple spaces.

**Comment by lukeocodes** [comment]
We'll pin v7 until we have a moment to discuss a change to our auth service. Thanks for your help

**Comment by orgads** [comment]
@lukeocodes In my case, it won't help, because I use v8, and I assign the global `WebSocket` to v8. If nobody else complained, I don't think you have a reason to pin it. I'll stick with 3.3.5 until there's a proper fix.

**Comment by lukeocodes** [comment]
@orgads we now have a PR in review to resolve this on our service. I will let you know once it has been released

**Comment by orgads** [comment]
Thank you!

**Comment by mozziebr** [comment]
@lukeocodes - I'm using production server websocket. Is this fix also resolved for this? 
https://developers.deepgram.com/reference/listen-live#endpoint
