### ISSUE TITLE
Deegpgram send random messgaes

### ISSUE THREAD

**Issue by piyuxx** [deepgram/deepgram-js-sdk#327]
I used mediarecroder torecord the stream and when the socket is opened i will send the available data to the deepgram socket , but i recieved the random messages in this process.
 i send the message to the deepgram socket and  i recieved the randoom messgaes sometimes, it cause major issue when it comes with is_final =true  and speech_final= true .I already check your discord channel , you replied the solution the random message confidence is low, but when i check it's almost same like 0.7,0.8. You also said in background noise the speech_finaal and is_final true in baackground noises. sometimes, i'm in empty room and it sends random message continously. And when mic is off , i cut the micropone access andd it continously send random message "okay" , background noise is not the issue in this case. Please provide the solution of this problem
 Here's a response i recieved and you can clearly see the is_final is true with a high confidence , the room is empty , no noise still got the random message. 

 {"type":"Results","channel_index":[0,1],"duration":1.8200073,"start":213.7,"is_final":true,"speech_final":true,"channel":{"alternatives":[{"transcript":"Okay.","confidence":0.9650879,"words":[{"word":"okay","start":215.06,"end":215.52,"confidence":0.9650879,"punctuated_word":"Okay."}]}]},"metadata":{"request_id":"b256ada4-7f7b-4b2b-a33d-ac438dead258","model_info":{"name":"2-ea-nova","version":"2023-09-18.22988","arch":"nova-2"},"model_uuid":"79dd3ac5-776e-4fcf-b4fb-0f9968bac445"},"from_finalize":false}

**Comment by lukeocodes** [comment]
Hi this is an issue with the API not the SDK, I will be closing it
