### ISSUE TITLE
Websocket connection closing abruptly in both Text to Speech and Speech to Text.

### ISSUE THREAD

**Issue by MD-AZMAL** [deepgram/deepgram-js-sdk#337]
## What is the current behavior?

The WebSocket connection to Deepgram abruptly closes while using live speech or live listen while running locally. I haven't tried this in production yet. There is no error event fired before closing, I get a metadata event after it is closed. so it is difficult to diagnose what has happened. The sample metadata event for live listen is as follows for reference:

```
{
  "type": "Metadata",
  "transaction_key": "deprecated",
  "request_id": "SOME_ID,
  "sha256": "SOME_HASH",
  "created": "SOME_DATE",
  "duration": 0,
  "channels": 0
}
```

Also checking the request id in deepgram's account shows no error.

## Steps to reproduce

It happens occasionally while the server is running, initiate a live listen and live speech connection and it terminates frequently.

## Expected behavior

The connection should remain open until explicitly closed, or any error occurs.
## Please tell us about your environment

> We want to make sure the problem isn't specific to your operating system or programming language.
  
- **Operating System/Version:** Windows 11
- **Language:** Typescript
- **Browser:** Chrome
-  **deepgram/sdk:** 3.8.0

## Other information

I am attaching the code for both the speech to text and text to speech module below:
```TS
const deepgram = createClient("MY_API_KEY");

// custom websocket server
const wss = new WebSocket.Server({ server: server });

wss.on("connection", (ws) => {
  // create a new Live listen connection

  const liveListen = deepgram.listen.live({
    model: "nova-2",
    language: "en-US",
    smart_format: true,
    interim_results: true,
    utterance_end_ms: 1000,
    vad_events: true,
    endpointing: 300,
  });

  liveListen.on(LiveTranscriptionEvents.Open, () => {
    console.log("Live Listen Open");

    // keep alive loop every 8s
    setInterval(() => {
      liveListen.keepAlive(), 8 * 1000;
    });
  });

  liveListen.on(LiveTranscriptionEvents.Close, () => {
    console.log("Live Listen Close");
  });

  liveListen.on(LiveTranscriptionEvents.Error, (error) => {
    console.log("Live Listen ERROR====================================");
    console.log(error);
    console.log("====================================");
  });

  liveListen.on(LiveTranscriptionEvents.Metadata, (data) => {
    console.log("Live Listen METADATA====================================");
    console.log(JSON.stringify(data, null, 1));
    console.log("====================================");
  });

  liveListen.on(LiveTranscriptionEvents.Transcript, (data) => {
    console.log("Live Listen TRANSCRIPT====================================");
    console.log(data?.channel?.alternatives[0]?.transcript);
    console.log("====================================");
  });

  // create a new Live Speech connection

  const liveSpeak = deepgram.speak.live({
    model: "aura-asteria-en",
    encoding: "linear16",
    sample_rate: 16000,
  });

  liveSpeak.on(LiveTTSEvents.Open, () => {
    console.log("Live Speak Open");
  });

  liveSpeak.on(LiveTTSEvents.Close, () => {
    console.log("Live Speak Close");
  });

  liveSpeak.on(LiveTTSEvents.Error, (error) => {
    console.log("Live Speak ERROR====================================");
    console.log(error);
    console.log("====================================");
  });

  liveSpeak.on(LiveTTSEvents.Metadata, (data) => {
    console.log("Live Speak METADATA====================================");
    console.log(JSON.stringify(data, null, 1));
    console.log("====================================");
  });

  liveListen.on(LiveTTSEvents.Audio, (data) => {
    console.log("Live Speak AUDIO====================================");
    console.log(data);
    console.log("====================================");
  });

  liveListen.on(LiveTTSEvents.Flushed, () => {
    console.log("Live Speak Flushed");
  });

  ws.on("message", (data: string) => {
    const jsonData = JSON.parse(data);

    if(jsonData.transcribe) {
      liveListen.send(jsonData.text)
    } else {
      liveSpeak.send(jsonData.audioChunk)
    }
  })
});

```

One might argue that opening a new connection to deepgram for each new client connected to websocket server is the issue, but its not working even when a single client is connected locally.

**Comment by lukeocodes** [comment]
Can you provide results of your debugging output? Request IDs?

**Comment by MD-AZMAL** [comment]
Here are some metadata for speech to text
```JSON
{
  type: 'Metadata',
  transaction_key: 'deprecated',
  request_id: '0838f367-285e-430e-bfc7-8e444440ed83',
  sha256: '3f9026fc71f6dba172006d406dc962cf11242563009252694c21e114e31e0e97',
  created: '2024-10-09T16:57:51.029Z',
  duration: 0,
  channels: 0
}

{
  type: 'Metadata',
  transaction_key: 'deprecated',
  request_id: 'a0d522ba-9d09-4d4e-8be5-a6b6858de412',
  sha256: '3904a2e31c823116a1a414160d59bf3252268295c477cf7f35c8f622de679796',
  created: '2024-10-09T16:58:26.023Z',
  duration: 0,
  channels: 0
}
```

Also I'm making sure that I'm not sending any empty bytes, I'm checking the byte size of each chunk and only sending if its non zero

**Comment by MD-AZMAL** [comment]
Even if I am sending keepAlive every 3 seconds just to check if firing keepalive would keep it open, it doesn't work, I timed the connection, and it closed after roughly 8.3 seconds. This is happening in live listen even with keepalive, but for live speech there is no keepalive method exposed by the client

**Comment by faizulhaque** [comment]
It's happening with me as well. Here is the snapshot:
![Screenshot 2024-10-10 at 2 52 15 am](https://github.com/user-attachments/assets/5885cbc6-a49a-4243-9f05-6d1dc8ce9dbc)

**Comment by AliTruckpin** [comment]
I also have this problem:  
<img width="754" alt="Screenshot 2024-10-12 at 00 34 19" src="https://github.com/user-attachments/assets/83b64534-f521-4bd7-b678-1b48e255cf03">

**Comment by MD-AZMAL** [comment]
@faizulhaque @AliTruckpin can also check the logs in deepgram for the request id. In my case it's showing 101 in all cases but no sign of any errors

**Comment by faizulhaque** [comment]
> It's happening with me as well. Here is the snapshot: ![Screenshot 2024-10-10 at 2 52 15 am](https://private-user-images.githubusercontent.com/836298/375529897-5885cbc6-a49a-4243-9f05-6d1dc8ce9dbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3Mzc1MTksIm5iZiI6MTcyODczNzIxOSwicGF0aCI6Ii84MzYyOTgvMzc1NTI5ODk3LTU4ODVjYmM2LWE0OWEtNDI0My05ZjA1LTZkMWRjOGNlOWRiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMjQ2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDk5ODE2ZGU2MzFlZWFhYTM5MGM1NjJjNWNkMjM5ZTRlNWVlYjMwYTFhZjQyNzQ2ZDY4MTA1ODVlNzIyODI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0EfFzjtP4a_AwqZJ0EFdWM0tIMUc1V8Mork1m3z2d84)

@MD-AZMAL 
I don't see any error too. 
![image](https://github.com/user-attachments/assets/b68d8334-9666-42f3-8200-269f41b91e79)

@lukeocodes can you suggest what could be the issue? or any clue how to fix this issue?

**Comment by MD-AZMAL** [comment]
@lukeocodes any updates on how to resolve it?

**Comment by lukeocodes** [comment]
> Here are some metadata for speech to text
> 
> ```ts
> {
>   type: 'Metadata',
>   transaction_key: 'deprecated',
>   request_id: '0838f367-285e-430e-bfc7-8e444440ed83',
>   sha256: '3f9026fc71f6dba172006d406dc962cf11242563009252694c21e114e31e0e97',
>   created: '2024-10-09T16:57:51.029Z',
>   duration: 0,
>   channels: 0
> }
> 
> {
>   type: 'Metadata',
>   transaction_key: 'deprecated',
>   request_id: 'a0d522ba-9d09-4d4e-8be5-a6b6858de412',
>   sha256: '3904a2e31c823116a1a414160d59bf3252268295c477cf7f35c8f622de679796',
>   created: '2024-10-09T16:58:26.023Z',
>   duration: 0,
>   channels: 0
> }
> ```
> 
> Also I'm making sure that I'm not sending any empty bytes, I'm checking the byte size of each chunk and only sending if its non zero


I checked both request_IDs and we seem to have received empty or corrupted audio. Please double check you're sending containerised audio with headers, or set the encoding/sample rate correctly when connecting.

This doesn't appear to be an issue with the SDK so I closing this issue

**Comment by MD-AZMAL** [comment]
> > Here are some metadata for speech to text
> > ```ts
> > {
> >   type: 'Metadata',
> >   transaction_key: 'deprecated',
> >   request_id: '0838f367-285e-430e-bfc7-8e444440ed83',
> >   sha256: '3f9026fc71f6dba172006d406dc962cf11242563009252694c21e114e31e0e97',
> >   created: '2024-10-09T16:57:51.029Z',
> >   duration: 0,
> >   channels: 0
> > }
> > 
> > {
> >   type: 'Metadata',
> >   transaction_key: 'deprecated',
> >   request_id: 'a0d522ba-9d09-4d4e-8be5-a6b6858de412',
> >   sha256: '3904a2e31c823116a1a414160d59bf3252268295c477cf7f35c8f622de679796',
> >   created: '2024-10-09T16:58:26.023Z',
> >   duration: 0,
> >   channels: 0
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also I'm making sure that I'm not sending any empty bytes, I'm checking the byte size of each chunk and only sending if its non zero
> 
> I checked both request_IDs and we seem to have received empty or corrupted audio. Please double check you're sending containerised audio with headers, or set the encoding/sample rate correctly when connecting.
> 
> This doesn't appear to be an issue with the SDK so I closing this issue

I followed the example given by the deepgram repo in github, can you point me to the right resource?

**Comment by lukeocodes** [comment]
I've never set a custom frameRate. That could be what is causing this issue

**Comment by MD-AZMAL** [comment]
@SameOldNick thanks for this. As far as I recall, removing the framerate did work for me. Looks like this is still a relevant issue even after a year 😄
