### ISSUE TITLE
Diarization Inconsistencies with Nova-2 and Limited Language Support in Other Models

### ISSUE THREAD

**Issue by rizz-official** [deepgram/deepgram-js-sdk#351]
The diarization feature in Deepgram has the following issues:

Inconsistent Diarization with Nova-2:

Speaker detection is unreliable when using the nova-2 model with diarization enabled for supported languages.
Sometimes speakers are detected, but the diarization accuracy is low.
Diarization Limitations in Other Models:

Models like nova-phonecall and nova-medical do not support diarization for languages other than English.
Attempting diarization with non-English languages on these models results in a 400 Bad Request error.

**Comment by lukeocodes** [comment]
Hi @rizz-official this is unfortunately not an issue with the SDK so I will close it here. You're welcome to raise it on our [community Discord or GitHub discussions](https://community.deepgram.com).
